{
 "title": "ATP3 Runner Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\", exported_namespace=\"$namespace\"},exported_pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overwiev", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Pods Count",
   "type": "stat",
   "description": "Show the number of pods running in the namespace",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=\"$cluster\", exported_namespace=~\"$namespace\"}) or vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Container status (Namespace)",
   "type": "stat",
   "description": "Show the count of containers in  Waiting, and Terminated statuses.",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(exported_namespace)(kube_pod_container_status_waiting_reason{cluster=~\"$cluster\", exported_namespace=\"$namespace\"} == 1)  OR on() vector(0)",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum by(exported_namespace)(kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", exported_namespace=\"$namespace\", reason!=\"Completed\"} == 1)  OR on() vector(0)",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum by(exported_namespace)(kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", exported_namespace=\"$namespace\", reason=\"Completed\"} == 1)  OR on() vector(0)",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum by(exported_namespace)(kube_pod_container_status_running{cluster=~\"$cluster\", exported_namespace=\"$namespace\"} == 1)  OR on() vector(0)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Last Deployment Time",
   "type": "stat",
   "description": "Shows the last time of pod deployed",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_created{cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"$pod\"} * 1000",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "state-timeline",
   "description": "Shows pod states",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum((kube_pod_status_phase{cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"$pod\", phase=\"Failed\"} * 2) or (kube_pod_status_phase{cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"$pod\", phase=\"Pending\"} * 4) or\n(kube_pod_status_phase{cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"$pod\", phase=\"Running\"} * 8) or \n(kube_pod_status_phase{cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"$pod\", phase=\"Succeeded\"} * 16) or \n(kube_pod_status_phase{cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"$pod\", phase=\"Unknown\"} * 32)) by (exported_pod)",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "Not healthy pods (Namespace)",
   "type": "table",
   "description": "Show information about the reason the container is currently in waiting or terminated state",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{cluster=~\"$cluster\",exported_namespace=\"$namespace\"} == 1"
    },
    {
     "expr": "kube_pod_container_status_terminated_reason{cluster=~\"$cluster\",exported_namespace=\"$namespace\",reason!=\"Completed\"} == 1"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Memory Usage $pod",
   "type": "timeseries",
   "description": "Shows memory usage per container in pod against resource requests and limits",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 24 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!~\"\", image!=\"\"}) by (container)",
     "legendFormat": "usage: {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"$pod\"}) by(container)\n",
     "legendFormat": "requests: {{ container }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"$pod\"}) by(container)\n",
     "legendFormat": "limits: {{ container }}"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\", image=~\".*\"}) by (container)\n",
     "legendFormat": "rss: {{ container }}"
    }
   ]
  },
  {
   "title": "Memory Quota $pod",
   "type": "table",
   "description": "Shows memory quota usage by pod",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 24 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!~\"\", image!=\"\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container!~\"\", pod=~\"$pod\", image!=\"\"}) by (container) / sum(kube_pod_container_resource_requests{resource=\"memory\", exported_namespace=\"$namespace\", exported_pod=~\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container!~\"\", pod=~\"$pod\", image!=\"\"}) by (container) / sum(kube_pod_container_resource_limits{resource=\"memory\", exported_namespace=\"$namespace\", exported_pod=~\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container != \"\", container != \"POD\"}) by (container)"
    },
    {
     "expr": "sum(container_memory_cache{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container != \"\", container != \"POD\"}) by (container)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!~\"\", image!=\"\"}) by (image, container)"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU Usage $pod",
   "type": "timeseries",
   "description": "Shows CPU usage per container in pod against resource requests and limits",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 34 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by (namespace, pod, container)(\r\nrate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container!~\"\", name!=\"\", image!=\"\"}[2m]))) by (pod,container)",
     "legendFormat": "usage: {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"$pod\", resource=\"cpu\"}) by (exported_pod,container)\n",
     "legendFormat": "requests: {{ container }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\",exported_namespace=\"$namespace\", exported_pod=~\"$pod\"}) by (exported_pod,container)\n",
     "legendFormat": "limits: {{ container }}"
    }
   ]
  },
  {
   "title": "CPU Quota $pod",
   "type": "table",
   "description": "Shows CPU quota usage by pod",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 34 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "sum(sum by (namespace, container, name) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!~\"\", name!=\"\"}[5m]))) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"$pod\", container!~\"\", resource=\"cpu\"}) by (container)"
    },
    {
     "expr": " sum(sum by (namespace, container, name) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!~\"^(.*POD.*|)$\", name!=\"\"}[5m]))) by (container) / sum(kube_pod_container_resource_requests{cluster=\"$cluster\",  exported_namespace=\"$namespace\", exported_pod=~\"$pod\", container!~\"\", resource=\"cpu\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(sum by (namespace, container, name) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!~\"\", name!=\"\"}[5m]))) by (container) / sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(sum by (namespace, container, image) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!~\"\", name!=\"\"}[5m]))) by (container, image)"
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Disk I/O utilization $pod",
   "type": "timeseries",
   "description": "Shows data read/write per container",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 44 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\", container!~\"\"}[5m])",
     "legendFormat": "{{ container }} - {{ device }} - reads bytes"
    },
    {
     "expr": "rate(container_fs_writes_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\", container!~\"\"}[5m])",
     "legendFormat": "{{ container }} - {{ device }} -  written bytes"
    }
   ]
  },
  {
   "title": "Conteiner IOps $pod",
   "type": "timeseries",
   "description": "Count of writes/reads completed",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 44 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!~\"\"}[5m])",
     "legendFormat": " {{ container}} : {{ device }} reading"
    },
    {
     "expr": "rate(container_fs_writes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!~\"\"}[5m])",
     "legendFormat": "{{ container}} : {{ device }} writing"
    }
   ]
  }
 ]
}